### ISSUE TITLE
add Judd and Judd-Vos modifications 

### ISSUE THREAD

**Issue by tiagoams** [jobel-openscience/FUME#2]
If I understood this correctly, there is a disclaimer inn forel_ule_MERIS.ipynb against using the table FUI_CIE1931.tsv for wavelengths shorter than 460nm.  What would be needed to update to the modifications above? I would like to apply to OLCI which has ever shorter band 01 (400nm).

**Comment by tiagoams** [comment]
I have found the improved table in http://www.cvrl.org and upload to data and update the notebooks to use it. Let me know if you would accept pull requests.

**Comment by jobel-code** [comment]
@tiagoams yes, please do sent the pull request :)

**Comment by tiagoams** [comment]
OK, I will tidy up and make a pull request for adding a table with the include Judd-Vos corrections.

Meanwhile I have another branch in my fork where [I extended the code to process satellite images instead of point observations](https://github.com/tiagoams/FUME/blob/fuimages/forel_ule_OLCI.ipynb). I have moved the function to a module and included two OLCI example images. Please have a look and see if you want to bring (some of) those changes to you repo. If we have similar objectives I would be happy to keep contributing here, rather than just forging ahead on my fork :)

Finally, There have been several papers published on FU since 2013, and I wonder if there are any developments worth implementing for applying to satellite sensors.

Hue-Angle Product for Low to Medium Spatial Resolution Optical Satellite Sensors 
https://www.mdpi.com/2072-4292/10/2/180/htm 

True Colour Classification of Natural Waters with Medium-Spectral Resolution Satellites: SeaWiFS, MODIS, MERIS and OLCI  
https://www.mdpi.com/1424-8220/15/10/25663/htm#sensors-15-25663-s001 

Classifying Natural Waters with the Forel-Ule Colour Index System: Results, Applications, Correlations and Crowdsourcing 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4690980/#B35-ijerph-12-15044

**Comment by jobel-code** [comment]
@tiagoams  thank you so much for your collaboration. To be honest I have forgotten that I had this repo. So, it would be great to give it  life with your contributions 💯  :)

**Comment by jobel-openscience** [comment]
Merged @tiagoams pull request. Closing issue.
